[phases.setup]
aptPkgs = [
  "wget",
  "curl",
  "gnupg",
  "ca-certificates",
  "fonts-liberation",
  "libappindicator3-1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libc6",
  "libcairo2",
  "libcups2",
  "libdbus-1-3",
  "libgdk-pixbuf2.0-0",
  "libnspr4",
  "libnss3",
  "libx11-6",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libxss1",
  "libxtst6",
  "xdg-utils",
  "chromium-browser",
  "chromedriver"
]
